### ISSUE TITLE
Tagging build issues

### ISSUE THREAD

**Issue by brianclements** [mattes/fugu#10]
I can't get the tagging option to work when I build images.

```yaml
hub: &hub
  image: "radial/hub-base:latest"
  detach: true
  name: hub
  restart: always
  volumes-from:
    - logs
    - cache

hubDynamic:
  <<: *hub
  volumes:
    - /config
    - /data
    - /run

hubStatic:
  <<: *hub
```

Building "hubStatic from a different directory I run:
`fugu build --path hub/ hubStatic --tag="hub"`

But this names the resulting image the same as the source:

```
docker build --tag="radial/axle-base:latest" hub/
```
So I thought about ordering? Thinking that fugu had it's own --tag option...
```
○ fugu build --path hub/ --tag="hub" hubStatic
docker build hub/
```
no dice. What you think? Where does that --tag option go?
